### PR TITLE
Support secure websocket connections

### LINKED ISSUE #1525: Respect SSL option when connecting to websocket
### What's wrong?

When `https: true` option is set cosmos is loaded through `https://` protocol. Trying to load a websocket through insecure protocols `ws://` instead of `wss://` breaks the app.

### Steps to reproduce

1.  Edit `cosmos.config.json` by adding `https: true, { httpsOptions }`.
2.  Try to load cosmos through `https://`.
3.  Page won't load.

### Screenshots

Screenshot 2023-06-06 at 15 14 19

### Useful info

- Cosmos version: `6.0.0-beta.3`
- Cosmos config:

```js
{
  "globalImports": ["./webpack/global.css", "./front-end/config/cosmos.global.js"],
  "https": true,
  "httpsOptions": {
    "keyPath": "./sslcerts/development/server/cliniko.dev.key",
    "certPath": "./sslcerts/development/server/cliniko.dev.crt"
  },
  "plugins": ["react-cosmos-plugin-webpack"],
  "port": 5555,
  "rootDir": "../../",
  "watchDirs": [],
  "webpack": {
    "overridePath": "./front-end/config/cosmos.override"
  }
}
```

- Server terminal output.

```
[Cosmos] Using cosmos config found at front-end/config/cosmos.config.json
[Cosmos] Found 1 plugin: Webpack
[Cosmos] See you at https://localhost:5555
[Cosmos] Using default webpack config
[Cosmos] Overriding webpack config at front-end/config/cosmos.override.js
[Cosmos] Building webpack...
webpack built bb04ab5311aa00a580d2 in 12226ms
29 assets
2286 modules
webpack 5.76.1 compiled successfully in 12226 ms
```

- Browser console output.

(screenshot)

### PR DESCRIPTION
**Pull request by kmjennison**
Closes #1525.

### CODE REVIEW

**Comment by skidding** [comment]
@kmjennison Great contribution, thanks 🙌

Pushed the changes under `6.0.0-beta.6`.

Just an FYI, I made a subsequent PR (#1539) to clean up some stuff:

- Applied Prettier and removed ESLint supressions, otherwise left source code the same.
- Refactored the tests to be more in line with existing tests and practices. I can offer more details if you want.

Really appreciate taking the time to make the changes and test everything!

**Comment by kmjennison** [comment]
Wonderful, thanks for the follow-up! Glad I could help.

**Comment by kmjennison** [comment]
@skidding Are you sure this made it into the latest release? I installed v6.0.0-beta.6 and still see the insecure websocket. In addition, `cat node_modules/react-cosmos-dom/dist/domRendererConnect.js` shows:

```js
import { createPostMessageConnect, createWebSocketsConnect, } from 'react-cosmos-core';
import { isInsideCosmosPreviewIframe } from './utils/isInsideCosmosPreviewIframe.js';
export function createDomRendererConnect(playgroundUrl) {
    return isInsideCosmosPreviewIframe()
        ? createPostMessageConnect()
        : createWebSocketsConnect(getWebSocketsUrl(playgroundUrl));
}
function getWebSocketsUrl(playgroundUrl) {
    return playgroundUrl.replace(/^https?:/, 'ws:');
}
```

**Comment by skidding** [comment]
@kmjennison I think so. Make sure to install all Cosmos packages you use with `@next` . For example: `react-cosmos@next react-cosmos-plugin-vite@next etc`.

Also, you can browse the published code here: https://www.npmjs.com/package/react-cosmos-dom/v/6.0.0-beta.6 – the file you mentioned doesn't exist in this version.

**Comment by skidding** [comment]
@kmjennison Let me know if upgrading all packages worked, otherwise I'd like to help find the issue.

**Comment by kmjennison** [comment]
@skidding This is working and all good! My yarn.lock was resolving to an older canary release. Thanks!

**Pull request merged**
