### PR TITLE
Implemented fix for #333 plus tests

### PR DESCRIPTION
**Pull request by JohnRowleySEL**
I  implemented a fix for #333 as well as tests to prevent regression.

### CODE REVIEW

**Comment by JohnRowleySEL** [comment]
@skidding Looking at the CI error log it doesn't look like my changes are causing the test failure...

**Comment by skidding** [comment]
You're right. [This](https://github.com/react-cosmos/react-cosmos/issues/334) is breaking the build. Will take a look at your PR soon!

**Comment by skidding** [comment]
@JohnRowleySEL looking great! 

- Can you please use kebab case and rename `fixture_extensions.js` to `fixture-extensions.js`? 
- Optional: Could you pin the enzyme dep to `2.8.0` on this branch to solve the broken build until [the problem](https://github.com/airbnb/enzyme/issues/892) is clarified?

**Comment by skidding** [comment]
No need to worry about enzyme anymore!

**Comment by skidding** [comment]
@JohnRowleySEL looking forward to merge this as soon as you rename the new file using kebab case. Thanks!

**Comment by JohnRowleySEL** [comment]
Sorry for the delay, been extra busy with my main duties. Renamed the file!

**Comment by skidding** [comment]
Thanks!

**Pull request merged**
