### PR TITLE
react-cosmos-voyager

### LINKED ISSUE #268: Decouple file discovery from webpack package
## Need

The module that looks inside the user's codebase and gathers component and fixture paths, based on `componentPaths` and `fixturePaths` options, needs to:

- Be used independently, e.g. for an integration with [React Tree Snapshot Testing](https://facebook.github.io/jest/blog/2016/07/27/jest-14.html)
- Support advanced matching, for monorepos like this one (more below)

## Solution

Deliver a new package (maybe called `react-cosmos-voyager` for fun), that "Explores your codebase to find component and fixture files." This would fix all file matching problems for good and make `react-cosmos-webpack` a 1st class citizen.

Here are the use cases supported by this package (also test cases):

### Relative fixtures

```js
componentPaths: ['components']
```

```bash
components/Foo.js
components/nested/Bar.jsx
components/__fixtures__/Foo/blank.js
components/__fixtures__/nested/Bar/one.js
components/__fixtures__/nested/Bar/two.js
```

```js
components: {
  Foo: 'components/Foo.js',
  'nested/Bar': 'components/nested/Bar.jsx'
}
fixtures: {
  Foo: {
    blank: 'components/__fixtures__/Foo/blank.js'
  }
  'nested/Bar': {
    one: 'components/__fixtures__/nested/Bar/one.js',
    two: 'components/__fixtures__/nested/Bar/two.js'
  }
}
```

### Relative fixtures, component dir

```js
componentPaths: ['components']
```

```bash
components/Foo/Foo.js
components/Foo/__fixtures__/blank.js
components/nested/Bar/Bar.jsx
components/nested/Bar/__fixtures__/one.js
components/nested/Bar/__fixtures__/two.js
```

```js
components: {
  Foo: 'components/Foo/Foo.js',
  'nested/Bar': 'components/nested/Bar/Bar.jsx'
}
fixtures: {
  Foo: {
    blank: 'components/Foo/__fixtures__/blank.js'
  }
  'nested/Bar': {
    one: 'components/nested/Bar/__fixtures__/one.js',
    two: 'components/nested/Bar/__fixtures__/two.js'
  }
}
```

### External fixtures

```js
componentPaths: ['components']
fixturePaths: ['fixtures']
```

```bash
components/Foo.js
components/nested/Bar.jsx
fixtures/Foo/blank.js
fixtures/nested/Bar/one.js
fixtures/nested/Bar/two.js
```

```js
components: {
  Foo: 'components/Foo.js',
  'nested/Bar': 'components/nested/Bar.jsx'
}
fixtures: {
  Foo: {
    blank: 'fixtures/Foo/blank.js'
  }
  'nested/Bar': {
    one: 'fixtures/Bar/one.js',
    two: 'fixtures/Bar/two.js'
  }
}
```

### Separate packages

```js
componentPaths: [
  'packages/Foo/src/index.js',
  'packages/nested/Bar/src/index.jsx',
],
getComponentName: componentPath =>
  componentPath.match(/packages/(.+)/src/index/)[1],

```

```bash
packages/Foo/src/index.js
packages/Foo/src/__fixtures__/blank.js
packages/nested/Bar/src/index.jsx
packages/nested/Bar/src/__fixtures__/one.js
packages/nested/Bar/src/__fixtures__/two.js
```

```js
components: {
  Foo: 'packages/Foo/src/index.js',
  'nested/Bar': 'packages/nested/Bar/src/index.jsx'
}
fixtures: {
  Foo: {
    blank: 'packages/Foo/src/__fixtures__/blank.js'
  }
  'nested/Bar': {
    one: 'packages/nested/Bar/src/__fixtures__/one.js',
    two: 'packages/nested/Bar/src/__fixtures__/two.js'
  }
}
```

### Separate packages, external fixtures

```js
componentPaths: [
  'packages/Foo/src/index.js',
  'packages/nested/Bar/src/index.jsx',
],
fixturePaths: ['fixtures']
getComponentName: componentPath =>
  componentPath.match(/packages/(.+)/src/index/)[1],

```

```bash
packages/Foo/src/index.js
packages/nested/Bar/src/index.jsx
fixtures/Foo/blank.js
fixtures/nested/Bar/one.js
fixtures/nested/Bar/two.js
```

```js
components: {
  Foo: 'packages/Foo/src/index.js',
  'nested/Bar': 'packages/nested/Bar/src/index.jsx'
}
fixtures: {
  Foo: {
    blank: 'fixtures/Foo/blank.js'
  }
  'nested/Bar': {
    one: 'fixtures/nested/Bar/one.js',
    two: 'fixtures/nested/Bar/two.js'
  }
}
```

@ovidiubute @RadValentin @flaviusone @catalinmiron would this cover all your use cases? (hs-components, web-ui & insights)

### PR DESCRIPTION
**Pull request by skidding**
Fixes #268

### CODE REVIEW

**Comment by skidding** [comment]
@ovidiubute another tricky one, but the result is pretty awesome. Besides the separation of concern which enables stuff like Jest snapshotting, the webpack bundling has been redesign. In effect, the HMR is triggered on new components and fixtures as well, which means you don't even have to reload after creating a new component or fixture, let alone rebuild. Wanted to record a gif but LICEcap is failing on me.

**Comment by ovidiu-bute-hs** [comment]
One step closer to IDE integration 😉

**Comment by skidding** [comment]
@ovidiu-bute-hs are you aware of https://github.com/react-cosmos/react-cosmos-atom?

**Comment by ovidiubute** [comment]
Yes, but I didn't have time to test it out. Probably will, soon.

**Pull request merged**
