### PR TITLE
fix: Only call dismissRuntimeErrors in dev env #593

### LINKED ISSUE #593: Cosmos Export Broken?
### What's up?

Hi, I have a fairly complex project setup that's using React Cosmos for a "living styleguide". We automatically publish `cosmos-export` to GitHub pages and during our most recent upgrade (from React Cosmos 3.2.1 to 3.7.0) we noticed that the exported pages were failing at runtime with this error:
screenshot 2018-02-15 17 16 43

Hunting down that error message lead me to [`react-error-overlay`](https://github.com/facebook/create-react-app/blob/25184c4e91ebabd16fe1cde3d8630830e4a36a01/packages/react-error-overlay/src/index.js#L142), and it looks like as far back as Cosmos 3.3.0 you've been using the 4.0.0 version of that overlay alongside the 4.2.1 version of `react-dev-utils` which itself uses the 3.0.0 version of the overlay … uh, in case that's not clear:
```bash
$ npm list react-error-overlay
└─┬ react-cosmos@3.3.0
  ├─┬ react-dev-utils@4.2.1
  │ └── react-error-overlay@3.0.0
  └── react-error-overlay@4.0.0
```

### Mkay, tell me more...

I don't have time right this second to set up a simple example project, but I suspect the fix might be as simple as updating `react-dev-utils` to 5.0.0? Idk, maybe that major bump means there will be some breaking changes required for Cosmos too.

For now, we've reverted to Cosmos 3.2.1 and things seem fine.

- - -

Anyway, love this project, happy to help further debug if I can. ❤️

### PR DESCRIPTION
**Pull request by skidding**
Fixes #593

### CODE REVIEW

**Comment by skidding** [comment]
@xavcz @mysterycommand can you please take a look?

This issues seems to have been this: react-error-overlay is [only initialized in development](https://github.com/react-cosmos/react-cosmos/blob/585ba7ebb9c03afec111ed0327ef4703b528947a/packages/react-cosmos/src/client/react-error-overlay.js#L5-L39), yet we tried to call dismissErrorOverlay in any env.

See if my changes seem decent and I'll quickly publish a patch version. Thanks!

**Comment by skidding** [comment]
Published in `3.7.1`. Let me know if this fixes your issue!

**Comment by mysterycommand** [comment]
Hey! This works! Thanks for the super quick turn around! ❤️

**Comment by skidding** [comment]
@mysterycommand 🤘

**Pull request merged**
