### PR TITLE
Fix website accessibility issues

### PR DESCRIPTION
**Pull request by J-Kallunki**
- HTML document has to have a lang attribute
- Links for screenreaders must have discernible text, hide repeated link having image only
- *Build UIs that scale*, do not disable text scaling and zooming

### CODE REVIEW

**Comment by skidding** [comment]
@J-Kallunki Let me know if you need help with the changes I requested. I prefer not to merge and afterwards make the changes myself because that would result in a broken master build. Thanks!

**Comment by J-Kallunki** [comment]
Thank you and sorry for the basic mistakes

**Comment by J-Kallunki** [comment]
@skidding I think Styled Components needs serializer for Jest and snapshots:
https://github.com/styled-components/jest-styled-components#serializer

Do you wan't to just manually resolve this conflict of updated snapshot?

**Comment by skidding** [comment]
> Do you wan't to just manually resolve this conflict of updated snapshot?

Done. Thanks for your contribution!

> I think Styled Components needs serializer for Jest and snapshots

Good idea! Added in https://github.com/react-cosmos/react-cosmos/pull/1129

**Pull request merged**
