### PR TITLE
Upgrade to webpack 4

### PR DESCRIPTION
**Pull request by skidding**
What this means:
- The default webpack config will only work with webpack 4 and above
- Cosmos will still work with webpack 1+ with a custom webpack config. Not sure for how long, thought, as [latest webpack-dev-middleware (v3)](https://github.com/webpack/webpack-dev-middleware/releases/tag/v3.0.0) no longer has backwards compatibility and I assume we'll eventually have to upgrade. For now I think we'll have to live with this notice `DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead`

### CODE REVIEW

**Comment by skidding** [comment]
Merged this because I want to release a new beta (under `next` npm dist) and test this in a bunch of repos. But please review if anyone is interested. cc @xavcz

**Comment by skidding** [comment]
Update: Released under `react-cosmos@4.0.0-beta.2` or `react-cosmos@next`.

- Still works with webpack 1.15 in [this repo](https://github.com/react-cosmos/react-cosmos-webpack1-example/commit/c2eae733115f9364aaafb874d38de5487b6c8368) 👍
- Fails with Flatris repo (Next.js), where it's relying on default webpack config and Next.js uses webpack <4 👎

**Comment by skidding** [comment]
Sorry, mate!

Can you try `react-cosmos@4.0.0-beta.3`? Should be fine now. If not, worse case you go back to `beta.1`. Let me know.

**Comment by xavcz** [comment]
Haha no probs!

Will try tomorrow (now = 🍻💥)!

Thanks for releasing the next (pun intended) beta!

**Pull request merged**
